before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: packages
    maintainer: Elwin Stephan
    formats:
      - apk
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: elwin
      name: homebrew-tools

    commit_author:
      name: elwin
      email: elwin.stephan@gmail.com

    url_template: "https://github.com/elwin/franz/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/elwin/franz"
    description: "Your Swiss-Army Knife tool for interacting with Kafka."
snapcrafts:
  -
    name: franz-kafka
    summary: Franz
    description: "Your Swiss-Army Knife tool for interacting with Kafka."
    publish: true

nix:
  -
    name: franz
    url_template: "https://github.com/elwin/franz/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: elwin
      email: elwin.stephan@gmail.com

    commit_msg_template: "{{ .ProjectName }}: {{ .Tag }}"
    homepage: "https://github.com/elwin/franz"
    description: "Your Swiss-Army Knife tool for interacting with Kafka."

    repository:
      owner: elwin
      name: nix-tools
      branch: master

      pull_request:
        enabled: false
        draft: true

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/elwinstephan/